# Generated by Django 5.2.1 on 2025-05-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_opportunite', models.CharField(max_length=50, unique=True)),
                ('nom_client', models.CharField(max_length=255)),
                ('type_de_bien', models.CharField(choices=[('H', 'Habitation'), ('NH', 'Hors habitation')], max_length=3)),
                ('type_de_garantie', models.CharField(choices=[('DO', 'DO seule'), ('TRC', 'TRC seule'), ('DUO', 'Duo (DO + TRC)')], max_length=3)),
                ('destination_ouvrage', models.CharField(choices=[('H', 'Habitation'), ('NH', 'Non habitation')], max_length=3)),
                ('types_travaux', models.CharField(choices=[('NEUF', 'Ouvrage neuf'), ('RL', 'Rénovation légère'), ('RUR', 'Rénovation lourde')], max_length=4)),
                ('cout_ouvrage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presence_existant', models.BooleanField(default=False)),
                ('client_vip', models.BooleanField(default=False)),
                ('souhaite_rcmo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
