# Generated by Django 5.2.1 on 2025-05-29 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='nom_client',
        ),
        migrations.AddField(
            model_name='devis',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devis',
            name='type_de_garantie',
            field=models.CharField(choices=[('DO', 'DO seule'), ('TRC', 'TRC seule'), ('DUO', 'Duo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='devis',
            name='types_travaux',
            field=models.CharField(choices=[('NEUF', 'Neuf'), ('RL', 'Renov. légère'), ('RUR', 'Renov. lourde')], max_length=4),
        ),
    ]
